# Discord settings:

# Your bot's secret token. Keep this safe!
bot_token: YOUR_BOT_TOKEN_HERE

# Your bot's application ID.
client_id: YOUR_CLIENT_ID_HERE

# The Discord user ID of the bot's creator. This user will be named with the creator_name below.
creator_id: YOUR_CREATOR_ID_HERE

# The name to use for the creator in conversations.
creator_name: YourName

# The custom status message for the bot.
status_message: Hello

# Conversation settings
max_text: 100000       # Max characters per message in history.
max_images: 5          # Max images per message.
max_messages: 25       # Max number of messages in the conversation history.

# Response style and channel settings
use_plain_responses: false # If true, bot sends plain text instead of embeds.
allow_dms: true            # If true, bot will respond to direct messages.

# Permissions: Control who can use the bot and where.
permissions:
  users:
    admin_ids: [] # Users with admin rights (e.g., can change model).
    allowed_ids: [] # Whitelist of user IDs. If empty, all non-blocked users are allowed.
    blocked_ids: [] # Blacklist of user IDs.
  roles:
    allowed_ids: [] # Whitelist of role IDs.
    blocked_ids: [] # Blacklist of role IDs.
  channels:
    allowed_ids: [] # Whitelist of channel/category IDs.
    blocked_ids: [] # Blacklist of channel/category IDs.


# ------------------
# LLM settings:
# ------------------

providers:
  openai:
    base_url: https://api.openai.com/v1 # to use it with gemini put "https://generativelanguage.googleapis.com/v1beta/openai/" as the base url
    api_key: 
  x-ai:
    base_url: https://api.x.ai/v1
    api_key: 
  mistral:
    base_url: https://api.mistral.ai/v1
    api_key: 
  groq:
    base_url: https://api.groq.com/openai/v1
    api_key: 
  openrouter:
    base_url: https://openrouter.ai/api/v1
    api_key: 
  ollama:
    base_url: http://localhost:11434/v1
  lmstudio:
    base_url: http://localhost:1234/v1
  vllm:
    base_url: http://localhost:8000/v1

models:
  openai/gemini-2.5-flash-lite-preview-06-17:
    temperature: 1.0
    
  openai/gemini-2.0-flash:
    temperature: 1.0

# System Prompt: Defines the AI's core personality and instructions.
# The code will automatically add context about the date, time, and creator's name.
system_prompt: | # add your own lore/personality/prompt for the bot here
  Today's date is {date}. The current time is {time}.
